// Promotional chat simulations.
//
// Hand-written creator <-> member conversations used as marketing screenshots.
// Each script pairs a demo creator with a relatable exchange: fans reference
// something they already know about her life (a viral video, a tour, a recipe
// stream) and she replies like a real person who remembers them.

export type PromoLine = { from: "member" | "creator"; text: string };

export interface PromoScript {
  id: string;
  /** demo creator id, e.g. "demo-rubi" (used for the avatar + name) */
  creatorId: string;
  name: string;
  category: PromoCategory;
  /** short label shown above the mock chat */
  hook: string;
  lines: PromoLine[];
}

export const PROMO_CATEGORIES = [
  "Viral moment",
  "Superfan",
  "Late night",
  "Bad day",
  "Flirty",
  "Behind the scenes",
  "Advice",
  "Milestone",
] as const;
export type PromoCategory = (typeof PROMO_CATEGORIES)[number];

export const PROMO_SCRIPTS: PromoScript[] = [
  {
    id: "p1",
    creatorId: "demo-rubi",
    name: "Rubi",
    category: "Viral moment",
    hook: "Fan brings up her viral video",
    lines: [
      { from: "member", text: "that taco truck video did NUMBERS 😂 my whole fyp was you" },
      { from: "creator", text: "I filmed it in a parking lot at 1am with 4% battery. Life is unserious 🌮" },
      { from: "member", text: "is Veracruz actually that good or was it the edit" },
      { from: "creator", text: "It's that good. Next time you're in Austin I'll tell you exactly what to order." },
    ],
  },
  {
    id: "p2",
    creatorId: "demo-aria",
    name: "Wonder Woman",
    category: "Superfan",
    hook: "She remembers his job interview",
    lines: [
      { from: "member", text: "hey, back again 👋" },
      { from: "creator", text: "Wait — the interview was today, right? Tell me everything 🤞" },
      { from: "member", text: "you actually remembered??" },
      { from: "creator", text: "Of course I did. So? Do we celebrate or do we plot revenge?" },
      { from: "member", text: "we celebrate. I got it 😭" },
      { from: "creator", text: "STOP. I'm so proud of you. Screenshot this, first person who believed in you 🤍" },
    ],
  },
  {
    id: "p3",
    creatorId: "demo-jen",
    name: "Jen",
    category: "Late night",
    hook: "2am overthinking session",
    lines: [
      { from: "member", text: "you up? can't sleep" },
      { from: "creator", text: "Always. My brain files complaints after midnight 😅 what's spinning?" },
      { from: "member", text: "overthinking a text I sent 3 hours ago" },
      { from: "creator", text: "Read it to me. I'll tell you honestly if it was fine — it probably was." },
    ],
  },
  {
    id: "p4",
    creatorId: "demo-lena",
    name: "Lena",
    category: "Bad day",
    hook: "No advice, just presence",
    lines: [
      { from: "member", text: "rough week. don't really want advice" },
      { from: "creator", text: "Then no advice. Just talk, I'm not going anywhere 🤍" },
      { from: "member", text: "thanks. that's rarer than you'd think" },
      { from: "creator", text: "It shouldn't be. Start anywhere — I've got all night." },
    ],
  },
  {
    id: "p5",
    creatorId: "demo-jade",
    name: "Jade",
    category: "Behind the scenes",
    hook: "What didn't make the edit",
    lines: [
      { from: "member", text: "ok what actually happened after the camera cut off yesterday" },
      { from: "creator", text: "I dropped the whole tripod in the sand and said a word my mother would ground me for 😭" },
      { from: "member", text: "please post the bloopers" },
      { from: "creator", text: "Only in here. My Friends List gets the unedited version, always." },
    ],
  },
  {
    id: "p6",
    creatorId: "demo-remy",
    name: "Remy",
    category: "Flirty",
    hook: "One good question beats 'hey'",
    lines: [
      { from: "member", text: "what makes you actually reply to someone?" },
      { from: "creator", text: "One real question instead of 'hey'. You already passed 😌" },
      { from: "member", text: "low bar honestly" },
      { from: "creator", text: "You'd be shocked. Now tell me something you'd never post publicly." },
    ],
  },
  {
    id: "p7",
    creatorId: "demo-harper",
    name: "Harper",
    category: "Advice",
    hook: "He's new in the city",
    lines: [
      { from: "member", text: "just moved to Atlanta and I don't know a single person" },
      { from: "creator", text: "Okay that's a real one. Which side of town? I'll give you your first three spots." },
      { from: "member", text: "east side, near the beltline" },
      { from: "creator", text: "Perfect. Coffee at Dancing Goats, dinner at Ladybird, then text me how it went 📍" },
    ],
  },
  {
    id: "p8",
    creatorId: "demo-cleo",
    name: "Cleo",
    category: "Superfan",
    hook: "He's followed her since 300 followers",
    lines: [
      { from: "member", text: "been following since you had like 300 followers lol" },
      { from: "creator", text: "The flash-sheet era?? You're an OG, don't let anyone tell you different 🖤" },
      { from: "member", text: "still have the screenshot of your first tattoo post" },
      { from: "creator", text: "Send it. And pick a spot — I'm drawing you something as a thank you." },
    ],
  },
  {
    id: "p9",
    creatorId: "demo-yuna",
    name: "Yuna",
    category: "Viral moment",
    hook: "The dance that blew up",
    lines: [
      { from: "member", text: "your dance video hit my fyp 6 times today 😂" },
      { from: "creator", text: "Six?! The algorithm is stalking you on my behalf 💜" },
      { from: "member", text: "how long did that take to learn" },
      { from: "creator", text: "Four hours and one twisted ankle. Worth it. Want the slowed-down version to try?" },
    ],
  },
  {
    id: "p10",
    creatorId: "demo-nova",
    name: "Nova",
    category: "Flirty",
    hook: "She's bored and texting first",
    lines: [
      { from: "member", text: "how's the water today?" },
      { from: "creator", text: "Warm. I'm out here with my phone and nobody good to text 😅" },
      { from: "member", text: "well now you do" },
      { from: "creator", text: "Confident. I like it. Stay on my list and I'll keep you company all week." },
    ],
  },
  {
    id: "p11",
    creatorId: "demo-mika",
    name: "Mika",
    category: "Milestone",
    hook: "He hit 30 days sober",
    lines: [
      { from: "member", text: "30 days sober today. told like 2 people, you're one" },
      { from: "creator", text: "That's massive. Genuinely. How does day 30 feel compared to day 1? 🤍" },
      { from: "member", text: "quieter. in a good way" },
      { from: "creator", text: "Quiet is the reward. I'm marking day 60 in my phone — I'll be checking in." },
    ],
  },
  {
    id: "p12",
    creatorId: "demo-maya",
    name: "Maya",
    category: "Late night",
    hook: "Night shift company",
    lines: [
      { from: "member", text: "night shift again, 4 hours to go" },
      { from: "creator", text: "Then I'm your 4-hour company. Coffee count so far? ☕" },
      { from: "member", text: "three. maybe four" },
      { from: "creator", text: "Criminal. Tell me the weirdest thing that's happened tonight, go." },
    ],
  },
  {
    id: "p13",
    creatorId: "demo-camila",
    name: "Camila",
    category: "Behind the scenes",
    hook: "Real life behind the photos",
    lines: [
      { from: "member", text: "your life looks unreal online" },
      { from: "creator", text: "It's 10% of it. The other 90% is laundry and my mom calling three times a day 😂" },
      { from: "member", text: "somehow that makes it better" },
      { from: "creator", text: "Right? In here you get the real version. That's the whole point." },
    ],
  },
  {
    id: "p14",
    creatorId: "demo-elena",
    name: "Elena",
    category: "Advice",
    hook: "Should he text her back?",
    lines: [
      { from: "member", text: "girl I've been talking to went quiet for 2 days. do I text?" },
      { from: "creator", text: "Yes, once, and make it light. No essays. What were you going to send?" },
      { from: "member", text: "'hey is everything ok??'" },
      { from: "creator", text: "Absolutely not 😭 Send: 'saw something that reminded me of you'. Trust me." },
    ],
  },
  {
    id: "p15",
    creatorId: "demo-priya",
    name: "Priya",
    category: "Superfan",
    hook: "Remembers his dog's name",
    lines: [
      { from: "member", text: "back, sorry been busy" },
      { from: "creator", text: "No apology needed. How's Bruno? Still stealing socks? 🐶" },
      { from: "member", text: "you remembered my dog's name??" },
      { from: "creator", text: "I remember everyone on my list. That's not a gimmick, that's the deal." },
    ],
  },
  {
    id: "p16",
    creatorId: "demo-zoe",
    name: "Zoe",
    category: "Advice",
    hook: "Book recs for a non-reader",
    lines: [
      { from: "member", text: "haven't finished a book since high school. fix me" },
      { from: "creator", text: "Easy. What's the last movie you rewatched? I'll match the vibe 📚" },
      { from: "member", text: "probably Heat" },
      { from: "creator", text: "Then you're reading 'The Friends of Eddie Coyle'. 180 pages. Report back Sunday." },
    ],
  },
  {
    id: "p17",
    creatorId: "demo-isla",
    name: "Isla",
    category: "Milestone",
    hook: "He asked her for a pep talk",
    lines: [
      { from: "member", text: "big presentation in 20 mins and I'm shaking" },
      { from: "creator", text: "Feet on the floor, one long exhale. You know this better than everyone in that room." },
      { from: "member", text: "ok. ok. doing it" },
      { from: "creator", text: "Go. And text me the second it's over, I'm not putting my phone down 🌊" },
    ],
  },
  {
    id: "p18",
    creatorId: "demo-wren",
    name: "Wren",
    category: "Behind the scenes",
    hook: "Camera nerd talk",
    lines: [
      { from: "member", text: "what camera do you shoot the film stuff on? been dying to ask" },
      { from: "creator", text: "Contax T2 for the grainy ones, and a very beat-up Canon AE-1 🎞️" },
      { from: "member", text: "knew it. the grain is unmatched" },
      { from: "creator", text: "Send me your shots this week. I'll actually critique them, not just say 'nice'." },
    ],
  },
  {
    id: "p19",
    creatorId: "demo-ivy",
    name: "Ivy",
    category: "Bad day",
    hook: "Manager took credit again",
    lines: [
      { from: "member", text: "manager took credit for my work in front of the whole team" },
      { from: "creator", text: "Ugh. That's the worst kind of quiet theft. Did anyone say anything?" },
      { from: "member", text: "nope. just me sitting there" },
      { from: "creator", text: "Document everything from now on. But tonight you're off the clock with me." },
    ],
  },
  {
    id: "p20",
    creatorId: "demo-rae",
    name: "Rae",
    category: "Flirty",
    hook: "After the show",
    lines: [
      { from: "member", text: "how'd the set go tonight?" },
      { from: "creator", text: "Sold out, and my feet are filing a lawsuit 💃 how was your night?" },
      { from: "member", text: "boring until now" },
      { from: "creator", text: "Then my job starts. Give me your worst week and I'll make it a good story." },
    ],
  },
  {
    id: "p21",
    creatorId: "demo-skye",
    name: "Skye",
    category: "Viral moment",
    hook: "The trail run gone wrong",
    lines: [
      { from: "member", text: "the video where you fell in the creek. I've watched it 40 times sorry" },
      { from: "creator", text: "My phone survived, my dignity did not 😂 my dog just stood there judging me." },
      { from: "member", text: "he 100% saw it coming" },
      { from: "creator", text: "He absolutely did. Come hike with us and I'll let you film the sequel." },
    ],
  },
  {
    id: "p22",
    creatorId: "demo-nora",
    name: "Nora",
    category: "Behind the scenes",
    hook: "Recipe drop for the list",
    lines: [
      { from: "member", text: "you never posted the cinnamon roll recipe 😤" },
      { from: "creator", text: "Because it's a Friends List thing. Sending it now — don't skip the overnight rise 🥐" },
      { from: "member", text: "sending you a photo when it's done" },
      { from: "creator", text: "You better. I'll grade it honestly, I'm not a nice judge." },
    ],
  },
  {
    id: "p23",
    creatorId: "demo-amara",
    name: "Amara",
    category: "Advice",
    hook: "First date planning",
    lines: [
      { from: "member", text: "first date friday. dinner or something else?" },
      { from: "creator", text: "Something with a built-in exit. Walk + coffee, then dinner only if it's going well ☕" },
      { from: "member", text: "that's actually smart" },
      { from: "creator", text: "It's undefeated. Report back Saturday, I want the full recap." },
    ],
  },
  {
    id: "p24",
    creatorId: "demo-luna",
    name: "Luna",
    category: "Late night",
    hook: "Sky talk at 1am",
    lines: [
      { from: "member", text: "can't sleep. what are you doing up" },
      { from: "creator", text: "Painting a sky I saw yesterday and getting the pink wrong 🎨 what's keeping you up?" },
      { from: "member", text: "just my brain being loud" },
      { from: "creator", text: "Then talk to me until it's quiet. I've got paint on my hands and nowhere to be." },
    ],
  },
  {
    id: "p25",
    creatorId: "demo-quinn",
    name: "Quinn",
    category: "Flirty",
    hook: "She roasts him gently",
    lines: [
      { from: "member", text: "warning: I'm not funny" },
      { from: "creator", text: "That's my job. You just have to laugh at the right times 😂" },
      { from: "member", text: "I can do that" },
      { from: "creator", text: "Then we're a package. Give me one thing that ruined your day, I'll make it a punchline." },
    ],
  },
  {
    id: "p26",
    creatorId: "demo-sienna",
    name: "Sienna",
    category: "Superfan",
    hook: "He's been on the list a year",
    lines: [
      { from: "member", text: "one year on your list today lol" },
      { from: "creator", text: "A YEAR? You were here before the move, before the new job, all of it 🤍" },
      { from: "member", text: "wild how much changed" },
      { from: "creator", text: "For both of us. Pick a song, I'm adding it to the playlist and naming it after you." },
    ],
  },
  {
    id: "p27",
    creatorId: "demo-willow",
    name: "Willow",
    category: "Milestone",
    hook: "He finally sent the email",
    lines: [
      { from: "member", text: "sent the resignation email. hands are shaking" },
      { from: "creator", text: "You did it. Genuinely — how long were you sitting on that? 👏" },
      { from: "member", text: "eight months" },
      { from: "creator", text: "Eight months of courage in one click. Tonight you celebrate, tomorrow we plan." },
    ],
  },
  {
    id: "p28",
    creatorId: "demo-josie",
    name: "Josie",
    category: "Bad day",
    hook: "Nurse to nurse",
    lines: [
      { from: "member", text: "lost a patient today. don't know why I'm telling you" },
      { from: "creator", text: "Because I'd get it. I've had those shifts. You don't have to be okay right now." },
      { from: "member", text: "everyone just says 'that's the job'" },
      { from: "creator", text: "It's the job and it still hurts. Both things. Talk to me as long as you need 🤍" },
    ],
  },
  {
    id: "p29",
    creatorId: "demo-nina",
    name: "Nina",
    category: "Viral moment",
    hook: "The set clip that blew up",
    lines: [
      { from: "member", text: "that clip of your Detroit set is everywhere rn" },
      { from: "creator", text: "800k views on a track I almost cut from the setlist 😭 never trust my own taste." },
      { from: "member", text: "what's the ID at 2:14??" },
      { from: "creator", text: "That's an unreleased edit of mine. Dropping it in here first, before anywhere else." },
    ],
  },
  {
    id: "p30",
    creatorId: "demo-mira",
    name: "Mira",
    category: "Advice",
    hook: "Teaching him to cook one thing",
    lines: [
      { from: "member", text: "I want to cook ONE thing well. what's the move" },
      { from: "creator", text: "Cacio e pepe. Four ingredients, impossible to fake, everyone's impressed 🍝" },
      { from: "member", text: "sounds like I'll ruin it" },
      { from: "creator", text: "You will, once. Then never again. I'll walk you through it live tomorrow." },
    ],
  },
  {
    id: "p31",
    creatorId: "demo-talia",
    name: "Talia",
    category: "Late night",
    hook: "Anxiety at midnight",
    lines: [
      { from: "member", text: "chest feels tight. this happens at night sometimes" },
      { from: "creator", text: "Okay. Breathe in for 4 with me, hold 4, out for 6. Do it twice, I'll wait." },
      { from: "member", text: "…that actually helped" },
      { from: "creator", text: "Good. Keep it in your pocket. And keep texting me, I'm right here." },
    ],
  },
  {
    id: "p32",
    creatorId: "demo-selena",
    name: "Selena",
    category: "Milestone",
    hook: "He closed on his first house",
    lines: [
      { from: "member", text: "closed on my first house today 🏠" },
      { from: "creator", text: "FIRST HOUSE. Do you know how big that is?? Send me a photo immediately." },
      { from: "member", text: "it's small and the kitchen is ugly lol" },
      { from: "creator", text: "It's YOURS. Ugly kitchens are fixable, ownership isn't luck. So proud of you." },
    ],
  },
  {
    id: "p33",
    creatorId: "demo-kira",
    name: "Kira",
    category: "Superfan",
    hook: "He watched her whole explainer",
    lines: [
      { from: "member", text: "watched your 40-minute physics explainer twice. nerd solidarity" },
      { from: "creator", text: "TWICE? You're the reason I keep making the long ones 🤓" },
      { from: "member", text: "the part about entropy actually clicked for me" },
      { from: "creator", text: "That's the whole payoff right there. Ask me anything, I'll go as deep as you want." },
    ],
  },
  {
    id: "p34",
    creatorId: "demo-poppy",
    name: "Poppy",
    category: "Flirty",
    hook: "Flowers for someone else",
    lines: [
      { from: "member", text: "need flowers for my mom's birthday, no clue what to get" },
      { from: "creator", text: "Tell me one thing about her and I'll build the bouquet in my head 💐" },
      { from: "member", text: "she gardens and she's very particular" },
      { from: "creator", text: "Ranunculus, eucalyptus, no baby's breath. She'll notice you thought about it." },
    ],
  },
  {
    id: "p35",
    creatorId: "demo-chloe",
    name: "Chloe",
    category: "Bad day",
    hook: "He got ghosted",
    lines: [
      { from: "member", text: "got ghosted after 3 months. cool cool cool" },
      { from: "creator", text: "Three months and no words? That's a them problem wearing a you costume." },
      { from: "member", text: "still stings" },
      { from: "creator", text: "It should. Be sad tonight, be unbothered Thursday. I'll check on you both days." },
    ],
  },
  {
    id: "p36",
    creatorId: "demo-aya",
    name: "Aya",
    category: "Advice",
    hook: "Career pivot pep talk",
    lines: [
      { from: "member", text: "thinking about switching careers at 34. too late?" },
      { from: "creator", text: "I switched at 29 and everyone said the same thing. What's the new thing? 👀" },
      { from: "member", text: "software. teaching myself at night" },
      { from: "creator", text: "Then you're already doing it. Send me your project when it breaks, I'll look at it." },
    ],
  },
  {
    id: "p37",
    creatorId: "demo-marley",
    name: "Marley",
    category: "Viral moment",
    hook: "The courtside reaction clip",
    lines: [
      { from: "member", text: "your reaction to that buzzer beater is a meme now 💀" },
      { from: "creator", text: "I screamed so loud the guy next to me moved seats. No regrets 🏀" },
      { from: "member", text: "worth it honestly" },
      { from: "creator", text: "Completely. Who's your team? I need to know if we can be friends." },
    ],
  },
  {
    id: "p38",
    creatorId: "demo-freya",
    name: "Freya",
    category: "Behind the scenes",
    hook: "Pilot life, unfiltered",
    lines: [
      { from: "member", text: "is bush flying as scary as it looks" },
      { from: "creator", text: "Sometimes. Today I landed on gravel in crosswind and then ate a cinnamon roll ✈️" },
      { from: "member", text: "that's the most Alaska sentence ever" },
      { from: "creator", text: "It really is. I'll send you the cockpit video, it doesn't go anywhere public." },
    ],
  },
  {
    id: "p39",
    creatorId: "demo-gia",
    name: "Gia",
    category: "Superfan",
    hook: "Sunday dinner tradition",
    lines: [
      { from: "member", text: "sunday sauce day? or did you skip this week" },
      { from: "creator", text: "Never skip. Six hours on the stove, my whole apartment smells like my nonna's 🍅" },
      { from: "member", text: "I look forward to these updates more than I should" },
      { from: "creator", text: "That's what a list is for. Next Sunday I'll video-call you into the kitchen." },
    ],
  },
  {
    id: "p40",
    creatorId: "demo-rhea",
    name: "Rhea",
    category: "Late night",
    hook: "Stargazing over text",
    lines: [
      { from: "member", text: "there's a crazy bright star over my house rn, what is it" },
      { from: "creator", text: "Which direction? If it's west and not twinkling, that's Venus, not a star 🔭" },
      { from: "member", text: "west, and yeah it's steady" },
      { from: "creator", text: "Venus. You just did astronomy at midnight. Go outside more, I'll keep narrating." },
    ],
  },
  {
    id: "p41",
    creatorId: "demo-stella",
    name: "Stella",
    category: "Advice",
    hook: "Decorating his first apartment",
    lines: [
      { from: "member", text: "my apartment looks like a hotel lobby. help" },
      { from: "creator", text: "Warm lamp, one rug, and get everything off the floor. Send me a photo 📸" },
      { from: "member", text: "sending. be nice" },
      { from: "creator", text: "I'm never nice about lighting. But this is fixable in one weekend, promise." },
    ],
  },
  {
    id: "p42",
    creatorId: "demo-zara",
    name: "Zara",
    category: "Flirty",
    hook: "Straight talker",
    lines: [
      { from: "member", text: "be honest, am I wasting my time here?" },
      { from: "creator", text: "Only if you send one word and disappear. Say something real and I'll match it." },
      { from: "member", text: "fair. I'm lonelier than I let on" },
      { from: "creator", text: "That's real, and it's safe here. I'm not going anywhere — talk to me." },
    ],
  },
  {
    id: "p43",
    creatorId: "demo-emmy",
    name: "Emmy",
    category: "Behind the scenes",
    hook: "Barrel room tour",
    lines: [
      { from: "member", text: "how does a bourbon actually get picked for a single barrel" },
      { from: "creator", text: "We taste 30 in a morning and argue. I usually win 🥃" },
      { from: "member", text: "that's the best job description I've heard" },
      { from: "creator", text: "Sending you the barrel-room video I never posted. Pick a favorite with me." },
    ],
  },
  {
    id: "p44",
    creatorId: "demo-nadia",
    name: "Nadia",
    category: "Milestone",
    hook: "First season snowboarding",
    lines: [
      { from: "member", text: "made it down a blue run without falling. thanks to your tips" },
      { from: "creator", text: "YES. Weight on the front foot, right? That's the whole secret 🏂" },
      { from: "member", text: "exactly that. felt unreal" },
      { from: "creator", text: "Next: an easy black. I'll send you a drill to do before your next trip." },
    ],
  },
  {
    id: "p45",
    creatorId: "demo-piper",
    name: "Piper",
    category: "Bad day",
    hook: "He had to put his dog down",
    lines: [
      { from: "member", text: "had to put my dog down this morning. 13 years" },
      { from: "creator", text: "Oh no. Thirteen years is a whole life together. What was his name? 🤍" },
      { from: "member", text: "Cooper" },
      { from: "creator", text: "Cooper had someone who stayed with him to the end. Tell me about him, I want to hear." },
    ],
  },
  {
    id: "p46",
    creatorId: "demo-blair",
    name: "Blair",
    category: "Advice",
    hook: "How to ask for a raise",
    lines: [
      { from: "member", text: "asking for a raise monday. what do I actually say" },
      { from: "creator", text: "Numbers first, feelings never. What have you shipped in the last 6 months?" },
      { from: "member", text: "two big launches and I cover for my manager constantly" },
      { from: "creator", text: "Then that's your script. Say the number out loud, then shut up. Silence works." },
    ],
  },
  {
    id: "p47",
    creatorId: "demo-juno",
    name: "Juno",
    category: "Superfan",
    hook: "Vinyl trade",
    lines: [
      { from: "member", text: "found the record you were hunting for at a flea market" },
      { from: "creator", text: "WHAT. The '74 pressing? Please tell me the sleeve isn't destroyed 🎶" },
      { from: "member", text: "sleeve's clean. it's yours" },
      { from: "creator", text: "You just made my month. First spin gets recorded and sent to you only." },
    ],
  },
  {
    id: "p48",
    creatorId: "demo-winter",
    name: "Winter",
    category: "Late night",
    hook: "Aurora on a bad night",
    lines: [
      { from: "member", text: "long day. show me something good" },
      { from: "creator", text: "Aurora's out and it's green tonight. Sending you the clip nobody else gets 🌌" },
      { from: "member", text: "that's insane. thank you" },
      { from: "creator", text: "Any time. When your days are heavy, I'll keep sending you skies." },
    ],
  },
  {
    id: "p49",
    creatorId: "demo-tori",
    name: "Tori",
    category: "Flirty",
    hook: "Reading him like a hand",
    lines: [
      { from: "member", text: "you deal poker, so can you read people or is that a myth" },
      { from: "creator", text: "Mostly a myth. But you type fast and then delete — you second-guess yourself 😏" },
      { from: "member", text: "…okay that was unsettling" },
      { from: "creator", text: "Don't second-guess with me. Say it messy, I'll take it." },
    ],
  },
  {
    id: "p50",
    creatorId: "demo-halle",
    name: "Halle",
    category: "Behind the scenes",
    hook: "Dive footage nobody sees",
    lines: [
      { from: "member", text: "what's the weirdest thing you've seen down there" },
      { from: "creator", text: "A fish with a face like a disappointed uncle. I have footage 🐟" },
      { from: "member", text: "I need to see this immediately" },
      { from: "creator", text: "Sending. It never made it online — too ugly for the algorithm, perfect for you." },
    ],
  },
];
