import { createFileRoute, Link } from "@tanstack/react-router";
import { LegalDoc, Section, Bullets } from "@/components/LegalDoc";
import { LEGAL } from "@/lib/legal";
import { pageHead } from "@/lib/seo";

export const Route = createFileRoute("/legal/ai-companions")({
  head: () =>
    pageHead({
      path: "/legal/ai-companions",
      title: "AI Companion Disclosure \u2014 Crush Chat",
      description:
        "How Crush labels AI companions: every AI-generated character is badged on its card, profile and chat header, replies are software-generated, and no AI persona is presented as a real person.",
      type: "article",
    }),
  component: AiCompanions,
});

function AiCompanions() {
  return (
    <LegalDoc
      title="AI Companion Disclosure"
      subtitle={`Some characters on ${LEGAL.productName} are AI companions. This page explains exactly how they are labelled, what they can and cannot do, and what you are paying for.`}
    >
      <Section heading="1. AI companions are labelled everywhere they appear">
        <Bullets
          items={[
            'Every AI character carries a persistent "AI companion" badge on its discovery card, on its profile header, and in the chat header.',
            'Opening a chat with an AI character shows an in-conversation notice: "This is an AI-generated character, not a real person. Replies are produced by software."',
            "AI characters are never described as available for meeting, dating, calls, or any real-world service.",
            "Human creators are separate accounts that complete identity and 18+ verification; they are never labelled as AI, and AI characters are never labelled as human.",
          ]}
        />
      </Section>

      <Section heading="2. What an AI companion is">
        <p>
          An AI companion is a fictional character whose replies are generated by a large language model. It has no
          feelings, no independent existence, and no ability to meet, call or transact with you. Conversations are
          entertainment. Anything an AI companion says is fictional and must not be relied on as advice of any kind
          (medical, legal, financial or otherwise).
        </p>
      </Section>

      <Section heading="3. Safety rules applied to every AI conversation">
        <Bullets
          items={[
            "All AI conversations run under a system policy that prohibits sexual and sexually suggestive content, innuendo, body talk, roleplay of sexual acts, and any promise of explicit media.",
            "The assistant declines and redirects on the first attempt and ends the conversation on repeat attempts.",
            "AI companions never request money, gifts, coins, personal financial details or off-platform contact.",
            "Attempts to involve minors, trafficking, or commercial sexual services trigger immediate termination and escalation, including NCMEC and law-enforcement referral where applicable.",
          ]}
        />
      </Section>

      <Section heading="4. What you pay for">
        <Bullets
          items={[
            "AI conversations are free to start. A limited number of free replies is available per AI character with no payment and no account.",
            <>
              Continued messaging is included in a Crush Gold or Crush Diamond membership (see{" "}
              <Link to="/legal/pricing" className="font-semibold text-primary">
                Pricing
              </Link>
              ). You are paying for access to the messaging feature, never for a message quota or per-message credit.
            </>,
            "Coins are never required to send or receive a message with an AI companion or a human creator.",
          ]}
        />
      </Section>

      <Section heading="5. AI characters are placeholders for human creators">
        <p>
          {LEGAL.productName} is built as a platform for human creators. While the creator community is still growing,
          a portion of the characters you see are AI companions that hold those slots so the experience is not empty.
          They are a temporary seed layer, not the end state of the product.
        </p>
        <Bullets
          items={[
            "As real creators join and complete identity and 18+ verification, they take the place of AI characters, which are retired from discovery.",
            "An AI character is never converted into a human profile and a human profile is never converted into an AI character. Replacement means the AI listing is removed and a separate, verified human account appears.",
            "Whatever the mix at any moment, the labelling rules in section 1 always apply: if it is AI, it is badged as AI everywhere it appears, in real time.",
            "Members can create their own profiles with a display name, bio and uploaded photos or videos at any time; all uploads pass automated review before they are visible.",
          ]}
        />
      </Section>

      <Section heading="6. Data and your control">
        <Bullets
          items={[
            "AI conversation text is processed by our model provider solely to generate a reply, and is not used to train third-party public models.",
            <>
              You can delete your conversations and your account at any time — see{" "}
              <Link to="/legal/delete-account" className="font-semibold text-primary">
                Delete your account &amp; data
              </Link>
              .
            </>,
            <>
              Questions or concerns:{" "}
              <a className="font-semibold text-primary" href={`mailto:${LEGAL.supportEmail}`}>
                {LEGAL.supportEmail}
              </a>
              .
            </>,
          ]}
        />
      </Section>
    </LegalDoc>
  );
}
