/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as CoinsRouteImport } from './routes/coins'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms.index'
import { Route as LegalIndexRouteImport } from './routes/legal.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SoonFeatureRouteImport } from './routes/soon.$feature'
import { Route as RoomsNewRouteImport } from './routes/rooms.new'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms.$roomId'
import { Route as LegalTrustRouteImport } from './routes/legal.trust'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalRefundsRouteImport } from './routes/legal.refunds'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalPricingRouteImport } from './routes/legal.pricing'
import { Route as LegalLawEnforcementRouteImport } from './routes/legal.law-enforcement'
import { Route as LegalDmcaRouteImport } from './routes/legal.dmca'
import { Route as LegalCreatorsRouteImport } from './routes/legal.creators'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalContactRouteImport } from './routes/legal.contact'
import { Route as LegalBillingRouteImport } from './routes/legal.billing'
import { Route as LegalAcceptableUseRouteImport } from './routes/legal.acceptable-use'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as HostRoomsRouteImport } from './routes/host.rooms'
import { Route as HostPricingRouteImport } from './routes/host.pricing'
import { Route as HostOnboardingRouteImport } from './routes/host.onboarding'
import { Route as HostMembersRouteImport } from './routes/host.members'
import { Route as HostInvitesRouteImport } from './routes/host.invites'
import { Route as HostHostIdRouteImport } from './routes/host.$hostId'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as ChatHostIdRouteImport } from './routes/chat.$hostId'
import { Route as ApiHostChatRouteImport } from './routes/api/host-chat'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminWarRoomRouteImport } from './routes/admin.war-room'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminShowcaseBrainRouteImport } from './routes/admin.showcase-brain'
import { Route as AdminShowcaseRouteImport } from './routes/admin.showcase'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminKycRouteImport } from './routes/admin.kyc'
import { Route as AdminHostsRouteImport } from './routes/admin.hosts'
import { Route as AdminEarlyAccessRouteImport } from './routes/admin.early-access'
import { Route as AdminCopilotRouteImport } from './routes/admin.copilot'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ChatUserUserIdRouteImport } from './routes/chat.user.$userId'
import { Route as ApiPublicDemoChatRouteImport } from './routes/api/public/demo-chat'
import { Route as AdminHostsHostIdRouteImport } from './routes/admin.hosts.$hostId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksShowcaseBrainRouteImport } from './routes/api/public/hooks/showcase-brain'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinsRoute = CoinsRouteImport.update({
  id: '/coins',
  path: '/coins',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SoonFeatureRoute = SoonFeatureRouteImport.update({
  id: '/soon/$feature',
  path: '/soon/$feature',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsNewRoute = RoomsNewRouteImport.update({
  id: '/rooms/new',
  path: '/rooms/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTrustRoute = LegalTrustRouteImport.update({
  id: '/legal/trust',
  path: '/legal/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundsRoute = LegalRefundsRouteImport.update({
  id: '/legal/refunds',
  path: '/legal/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPricingRoute = LegalPricingRouteImport.update({
  id: '/legal/pricing',
  path: '/legal/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalLawEnforcementRoute = LegalLawEnforcementRouteImport.update({
  id: '/legal/law-enforcement',
  path: '/legal/law-enforcement',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDmcaRoute = LegalDmcaRouteImport.update({
  id: '/legal/dmca',
  path: '/legal/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCreatorsRoute = LegalCreatorsRouteImport.update({
  id: '/legal/creators',
  path: '/legal/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalContactRoute = LegalContactRouteImport.update({
  id: '/legal/contact',
  path: '/legal/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalBillingRoute = LegalBillingRouteImport.update({
  id: '/legal/billing',
  path: '/legal/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAcceptableUseRoute = LegalAcceptableUseRouteImport.update({
  id: '/legal/acceptable-use',
  path: '/legal/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoomsRoute = HostRoomsRouteImport.update({
  id: '/host/rooms',
  path: '/host/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const HostPricingRoute = HostPricingRouteImport.update({
  id: '/host/pricing',
  path: '/host/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HostOnboardingRoute = HostOnboardingRouteImport.update({
  id: '/host/onboarding',
  path: '/host/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HostMembersRoute = HostMembersRouteImport.update({
  id: '/host/members',
  path: '/host/members',
  getParentRoute: () => rootRouteImport,
} as any)
const HostInvitesRoute = HostInvitesRouteImport.update({
  id: '/host/invites',
  path: '/host/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const HostHostIdRoute = HostHostIdRouteImport.update({
  id: '/host/$hostId',
  path: '/host/$hostId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatHostIdRoute = ChatHostIdRouteImport.update({
  id: '/chat/$hostId',
  path: '/chat/$hostId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHostChatRoute = ApiHostChatRouteImport.update({
  id: '/api/host-chat',
  path: '/api/host-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWarRoomRoute = AdminWarRoomRouteImport.update({
  id: '/war-room',
  path: '/war-room',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShowcaseBrainRoute = AdminShowcaseBrainRouteImport.update({
  id: '/showcase-brain',
  path: '/showcase-brain',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShowcaseRoute = AdminShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHostsRoute = AdminHostsRouteImport.update({
  id: '/hosts',
  path: '/hosts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEarlyAccessRoute = AdminEarlyAccessRouteImport.update({
  id: '/early-access',
  path: '/early-access',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCopilotRoute = AdminCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AdminRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChatUserUserIdRoute = ChatUserUserIdRouteImport.update({
  id: '/chat/user/$userId',
  path: '/chat/user/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDemoChatRoute = ApiPublicDemoChatRouteImport.update({
  id: '/api/public/demo-chat',
  path: '/api/public/demo-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHostsHostIdRoute = AdminHostsHostIdRouteImport.update({
  id: '/$hostId',
  path: '/$hostId',
  getParentRoute: () => AdminHostsRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksShowcaseBrainRoute =
  ApiPublicHooksShowcaseBrainRouteImport.update({
    id: '/api/public/hooks/showcase-brain',
    path: '/api/public/hooks/showcase-brain',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRoute
  '/coins': typeof CoinsRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/mcp': typeof McpRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/upgrade': typeof UpgradeRoute
  '/verify': typeof VerifyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/copilot': typeof AdminCopilotRoute
  '/admin/early-access': typeof AdminEarlyAccessRoute
  '/admin/hosts': typeof AdminHostsRouteWithChildren
  '/admin/kyc': typeof AdminKycRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/showcase': typeof AdminShowcaseRoute
  '/admin/showcase-brain': typeof AdminShowcaseBrainRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/war-room': typeof AdminWarRoomRoute
  '/api/chat': typeof ApiChatRoute
  '/api/host-chat': typeof ApiHostChatRoute
  '/chat/$hostId': typeof ChatHostIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/host/$hostId': typeof HostHostIdRoute
  '/host/invites': typeof HostInvitesRoute
  '/host/members': typeof HostMembersRoute
  '/host/onboarding': typeof HostOnboardingRoute
  '/host/pricing': typeof HostPricingRoute
  '/host/rooms': typeof HostRoomsRoute
  '/invite/$code': typeof InviteCodeRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/billing': typeof LegalBillingRoute
  '/legal/contact': typeof LegalContactRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/creators': typeof LegalCreatorsRoute
  '/legal/dmca': typeof LegalDmcaRoute
  '/legal/law-enforcement': typeof LegalLawEnforcementRoute
  '/legal/pricing': typeof LegalPricingRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/legal/trust': typeof LegalTrustRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/rooms/new': typeof RoomsNewRoute
  '/soon/$feature': typeof SoonFeatureRoute
  '/admin/': typeof AdminIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/hosts/$hostId': typeof AdminHostsHostIdRoute
  '/api/public/demo-chat': typeof ApiPublicDemoChatRoute
  '/chat/user/$userId': typeof ChatUserUserIdRoute
  '/api/public/hooks/showcase-brain': typeof ApiPublicHooksShowcaseBrainRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRoute
  '/coins': typeof CoinsRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/mcp': typeof McpRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/upgrade': typeof UpgradeRoute
  '/verify': typeof VerifyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/copilot': typeof AdminCopilotRoute
  '/admin/early-access': typeof AdminEarlyAccessRoute
  '/admin/hosts': typeof AdminHostsRouteWithChildren
  '/admin/kyc': typeof AdminKycRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/showcase': typeof AdminShowcaseRoute
  '/admin/showcase-brain': typeof AdminShowcaseBrainRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/war-room': typeof AdminWarRoomRoute
  '/api/chat': typeof ApiChatRoute
  '/api/host-chat': typeof ApiHostChatRoute
  '/chat/$hostId': typeof ChatHostIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/host/$hostId': typeof HostHostIdRoute
  '/host/invites': typeof HostInvitesRoute
  '/host/members': typeof HostMembersRoute
  '/host/onboarding': typeof HostOnboardingRoute
  '/host/pricing': typeof HostPricingRoute
  '/host/rooms': typeof HostRoomsRoute
  '/invite/$code': typeof InviteCodeRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/billing': typeof LegalBillingRoute
  '/legal/contact': typeof LegalContactRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/creators': typeof LegalCreatorsRoute
  '/legal/dmca': typeof LegalDmcaRoute
  '/legal/law-enforcement': typeof LegalLawEnforcementRoute
  '/legal/pricing': typeof LegalPricingRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/legal/trust': typeof LegalTrustRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/rooms/new': typeof RoomsNewRoute
  '/soon/$feature': typeof SoonFeatureRoute
  '/admin': typeof AdminIndexRoute
  '/legal': typeof LegalIndexRoute
  '/rooms': typeof RoomsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/hosts/$hostId': typeof AdminHostsHostIdRoute
  '/api/public/demo-chat': typeof ApiPublicDemoChatRoute
  '/chat/user/$userId': typeof ChatUserUserIdRoute
  '/api/public/hooks/showcase-brain': typeof ApiPublicHooksShowcaseBrainRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRoute
  '/coins': typeof CoinsRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/mcp': typeof McpRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/upgrade': typeof UpgradeRoute
  '/verify': typeof VerifyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/copilot': typeof AdminCopilotRoute
  '/admin/early-access': typeof AdminEarlyAccessRoute
  '/admin/hosts': typeof AdminHostsRouteWithChildren
  '/admin/kyc': typeof AdminKycRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/showcase': typeof AdminShowcaseRoute
  '/admin/showcase-brain': typeof AdminShowcaseBrainRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/war-room': typeof AdminWarRoomRoute
  '/api/chat': typeof ApiChatRoute
  '/api/host-chat': typeof ApiHostChatRoute
  '/chat/$hostId': typeof ChatHostIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/host/$hostId': typeof HostHostIdRoute
  '/host/invites': typeof HostInvitesRoute
  '/host/members': typeof HostMembersRoute
  '/host/onboarding': typeof HostOnboardingRoute
  '/host/pricing': typeof HostPricingRoute
  '/host/rooms': typeof HostRoomsRoute
  '/invite/$code': typeof InviteCodeRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/billing': typeof LegalBillingRoute
  '/legal/contact': typeof LegalContactRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/creators': typeof LegalCreatorsRoute
  '/legal/dmca': typeof LegalDmcaRoute
  '/legal/law-enforcement': typeof LegalLawEnforcementRoute
  '/legal/pricing': typeof LegalPricingRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/legal/trust': typeof LegalTrustRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/rooms/new': typeof RoomsNewRoute
  '/soon/$feature': typeof SoonFeatureRoute
  '/admin/': typeof AdminIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/hosts/$hostId': typeof AdminHostsHostIdRoute
  '/api/public/demo-chat': typeof ApiPublicDemoChatRoute
  '/chat/user/$userId': typeof ChatUserUserIdRoute
  '/api/public/hooks/showcase-brain': typeof ApiPublicHooksShowcaseBrainRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/chats'
    | '/coins'
    | '/copilot'
    | '/dashboard'
    | '/discover'
    | '/mcp'
    | '/profile'
    | '/sitemap.xml'
    | '/subscriptions'
    | '/upgrade'
    | '/verify'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/copilot'
    | '/admin/early-access'
    | '/admin/hosts'
    | '/admin/kyc'
    | '/admin/payouts'
    | '/admin/showcase'
    | '/admin/showcase-brain'
    | '/admin/users'
    | '/admin/war-room'
    | '/api/chat'
    | '/api/host-chat'
    | '/chat/$hostId'
    | '/checkout/return'
    | '/host/$hostId'
    | '/host/invites'
    | '/host/members'
    | '/host/onboarding'
    | '/host/pricing'
    | '/host/rooms'
    | '/invite/$code'
    | '/legal/acceptable-use'
    | '/legal/billing'
    | '/legal/contact'
    | '/legal/cookies'
    | '/legal/creators'
    | '/legal/dmca'
    | '/legal/law-enforcement'
    | '/legal/pricing'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/legal/trust'
    | '/rooms/$roomId'
    | '/rooms/new'
    | '/soon/$feature'
    | '/admin/'
    | '/legal/'
    | '/rooms/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/hosts/$hostId'
    | '/api/public/demo-chat'
    | '/chat/user/$userId'
    | '/api/public/hooks/showcase-brain'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chats'
    | '/coins'
    | '/copilot'
    | '/dashboard'
    | '/discover'
    | '/mcp'
    | '/profile'
    | '/sitemap.xml'
    | '/subscriptions'
    | '/upgrade'
    | '/verify'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/copilot'
    | '/admin/early-access'
    | '/admin/hosts'
    | '/admin/kyc'
    | '/admin/payouts'
    | '/admin/showcase'
    | '/admin/showcase-brain'
    | '/admin/users'
    | '/admin/war-room'
    | '/api/chat'
    | '/api/host-chat'
    | '/chat/$hostId'
    | '/checkout/return'
    | '/host/$hostId'
    | '/host/invites'
    | '/host/members'
    | '/host/onboarding'
    | '/host/pricing'
    | '/host/rooms'
    | '/invite/$code'
    | '/legal/acceptable-use'
    | '/legal/billing'
    | '/legal/contact'
    | '/legal/cookies'
    | '/legal/creators'
    | '/legal/dmca'
    | '/legal/law-enforcement'
    | '/legal/pricing'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/legal/trust'
    | '/rooms/$roomId'
    | '/rooms/new'
    | '/soon/$feature'
    | '/admin'
    | '/legal'
    | '/rooms'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/hosts/$hostId'
    | '/api/public/demo-chat'
    | '/chat/user/$userId'
    | '/api/public/hooks/showcase-brain'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/chats'
    | '/coins'
    | '/copilot'
    | '/dashboard'
    | '/discover'
    | '/mcp'
    | '/profile'
    | '/sitemap.xml'
    | '/subscriptions'
    | '/upgrade'
    | '/verify'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/copilot'
    | '/admin/early-access'
    | '/admin/hosts'
    | '/admin/kyc'
    | '/admin/payouts'
    | '/admin/showcase'
    | '/admin/showcase-brain'
    | '/admin/users'
    | '/admin/war-room'
    | '/api/chat'
    | '/api/host-chat'
    | '/chat/$hostId'
    | '/checkout/return'
    | '/host/$hostId'
    | '/host/invites'
    | '/host/members'
    | '/host/onboarding'
    | '/host/pricing'
    | '/host/rooms'
    | '/invite/$code'
    | '/legal/acceptable-use'
    | '/legal/billing'
    | '/legal/contact'
    | '/legal/cookies'
    | '/legal/creators'
    | '/legal/dmca'
    | '/legal/law-enforcement'
    | '/legal/pricing'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/legal/trust'
    | '/rooms/$roomId'
    | '/rooms/new'
    | '/soon/$feature'
    | '/admin/'
    | '/legal/'
    | '/rooms/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/hosts/$hostId'
    | '/api/public/demo-chat'
    | '/chat/user/$userId'
    | '/api/public/hooks/showcase-brain'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChatsRoute: typeof ChatsRoute
  CoinsRoute: typeof CoinsRoute
  CopilotRoute: typeof CopilotRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  McpRoute: typeof McpRoute
  ProfileRoute: typeof ProfileRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  UpgradeRoute: typeof UpgradeRoute
  VerifyRoute: typeof VerifyRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiHostChatRoute: typeof ApiHostChatRoute
  ChatHostIdRoute: typeof ChatHostIdRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  HostHostIdRoute: typeof HostHostIdRoute
  HostInvitesRoute: typeof HostInvitesRoute
  HostMembersRoute: typeof HostMembersRoute
  HostOnboardingRoute: typeof HostOnboardingRoute
  HostPricingRoute: typeof HostPricingRoute
  HostRoomsRoute: typeof HostRoomsRoute
  InviteCodeRoute: typeof InviteCodeRoute
  LegalAcceptableUseRoute: typeof LegalAcceptableUseRoute
  LegalBillingRoute: typeof LegalBillingRoute
  LegalContactRoute: typeof LegalContactRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalCreatorsRoute: typeof LegalCreatorsRoute
  LegalDmcaRoute: typeof LegalDmcaRoute
  LegalLawEnforcementRoute: typeof LegalLawEnforcementRoute
  LegalPricingRoute: typeof LegalPricingRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundsRoute: typeof LegalRefundsRoute
  LegalTermsRoute: typeof LegalTermsRoute
  LegalTrustRoute: typeof LegalTrustRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
  RoomsNewRoute: typeof RoomsNewRoute
  SoonFeatureRoute: typeof SoonFeatureRoute
  LegalIndexRoute: typeof LegalIndexRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicDemoChatRoute: typeof ApiPublicDemoChatRoute
  ChatUserUserIdRoute: typeof ChatUserUserIdRoute
  ApiPublicHooksShowcaseBrainRoute: typeof ApiPublicHooksShowcaseBrainRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coins': {
      id: '/coins'
      path: '/coins'
      fullPath: '/coins'
      preLoaderRoute: typeof CoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/soon/$feature': {
      id: '/soon/$feature'
      path: '/soon/$feature'
      fullPath: '/soon/$feature'
      preLoaderRoute: typeof SoonFeatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/new': {
      id: '/rooms/new'
      path: '/rooms/new'
      fullPath: '/rooms/new'
      preLoaderRoute: typeof RoomsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/trust': {
      id: '/legal/trust'
      path: '/legal/trust'
      fullPath: '/legal/trust'
      preLoaderRoute: typeof LegalTrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refunds': {
      id: '/legal/refunds'
      path: '/legal/refunds'
      fullPath: '/legal/refunds'
      preLoaderRoute: typeof LegalRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/pricing': {
      id: '/legal/pricing'
      path: '/legal/pricing'
      fullPath: '/legal/pricing'
      preLoaderRoute: typeof LegalPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/law-enforcement': {
      id: '/legal/law-enforcement'
      path: '/legal/law-enforcement'
      fullPath: '/legal/law-enforcement'
      preLoaderRoute: typeof LegalLawEnforcementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/dmca': {
      id: '/legal/dmca'
      path: '/legal/dmca'
      fullPath: '/legal/dmca'
      preLoaderRoute: typeof LegalDmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/creators': {
      id: '/legal/creators'
      path: '/legal/creators'
      fullPath: '/legal/creators'
      preLoaderRoute: typeof LegalCreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/contact': {
      id: '/legal/contact'
      path: '/legal/contact'
      fullPath: '/legal/contact'
      preLoaderRoute: typeof LegalContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/billing': {
      id: '/legal/billing'
      path: '/legal/billing'
      fullPath: '/legal/billing'
      preLoaderRoute: typeof LegalBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/acceptable-use': {
      id: '/legal/acceptable-use'
      path: '/legal/acceptable-use'
      fullPath: '/legal/acceptable-use'
      preLoaderRoute: typeof LegalAcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/rooms': {
      id: '/host/rooms'
      path: '/host/rooms'
      fullPath: '/host/rooms'
      preLoaderRoute: typeof HostRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/pricing': {
      id: '/host/pricing'
      path: '/host/pricing'
      fullPath: '/host/pricing'
      preLoaderRoute: typeof HostPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/onboarding': {
      id: '/host/onboarding'
      path: '/host/onboarding'
      fullPath: '/host/onboarding'
      preLoaderRoute: typeof HostOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/members': {
      id: '/host/members'
      path: '/host/members'
      fullPath: '/host/members'
      preLoaderRoute: typeof HostMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/invites': {
      id: '/host/invites'
      path: '/host/invites'
      fullPath: '/host/invites'
      preLoaderRoute: typeof HostInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$hostId': {
      id: '/host/$hostId'
      path: '/host/$hostId'
      fullPath: '/host/$hostId'
      preLoaderRoute: typeof HostHostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$hostId': {
      id: '/chat/$hostId'
      path: '/chat/$hostId'
      fullPath: '/chat/$hostId'
      preLoaderRoute: typeof ChatHostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/host-chat': {
      id: '/api/host-chat'
      path: '/api/host-chat'
      fullPath: '/api/host-chat'
      preLoaderRoute: typeof ApiHostChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/war-room': {
      id: '/admin/war-room'
      path: '/war-room'
      fullPath: '/admin/war-room'
      preLoaderRoute: typeof AdminWarRoomRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/showcase-brain': {
      id: '/admin/showcase-brain'
      path: '/showcase-brain'
      fullPath: '/admin/showcase-brain'
      preLoaderRoute: typeof AdminShowcaseBrainRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/showcase': {
      id: '/admin/showcase'
      path: '/showcase'
      fullPath: '/admin/showcase'
      preLoaderRoute: typeof AdminShowcaseRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hosts': {
      id: '/admin/hosts'
      path: '/hosts'
      fullPath: '/admin/hosts'
      preLoaderRoute: typeof AdminHostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/early-access': {
      id: '/admin/early-access'
      path: '/early-access'
      fullPath: '/admin/early-access'
      preLoaderRoute: typeof AdminEarlyAccessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/copilot': {
      id: '/admin/copilot'
      path: '/copilot'
      fullPath: '/admin/copilot'
      preLoaderRoute: typeof AdminCopilotRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/user/$userId': {
      id: '/chat/user/$userId'
      path: '/chat/user/$userId'
      fullPath: '/chat/user/$userId'
      preLoaderRoute: typeof ChatUserUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/demo-chat': {
      id: '/api/public/demo-chat'
      path: '/api/public/demo-chat'
      fullPath: '/api/public/demo-chat'
      preLoaderRoute: typeof ApiPublicDemoChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hosts/$hostId': {
      id: '/admin/hosts/$hostId'
      path: '/$hostId'
      fullPath: '/admin/hosts/$hostId'
      preLoaderRoute: typeof AdminHostsHostIdRouteImport
      parentRoute: typeof AdminHostsRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/showcase-brain': {
      id: '/api/public/hooks/showcase-brain'
      path: '/api/public/hooks/showcase-brain'
      fullPath: '/api/public/hooks/showcase-brain'
      preLoaderRoute: typeof ApiPublicHooksShowcaseBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminHostsRouteChildren {
  AdminHostsHostIdRoute: typeof AdminHostsHostIdRoute
}

const AdminHostsRouteChildren: AdminHostsRouteChildren = {
  AdminHostsHostIdRoute: AdminHostsHostIdRoute,
}

const AdminHostsRouteWithChildren = AdminHostsRoute._addFileChildren(
  AdminHostsRouteChildren,
)

interface AdminRouteChildren {
  AdminCopilotRoute: typeof AdminCopilotRoute
  AdminEarlyAccessRoute: typeof AdminEarlyAccessRoute
  AdminHostsRoute: typeof AdminHostsRouteWithChildren
  AdminKycRoute: typeof AdminKycRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminShowcaseRoute: typeof AdminShowcaseRoute
  AdminShowcaseBrainRoute: typeof AdminShowcaseBrainRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWarRoomRoute: typeof AdminWarRoomRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCopilotRoute: AdminCopilotRoute,
  AdminEarlyAccessRoute: AdminEarlyAccessRoute,
  AdminHostsRoute: AdminHostsRouteWithChildren,
  AdminKycRoute: AdminKycRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminShowcaseRoute: AdminShowcaseRoute,
  AdminShowcaseBrainRoute: AdminShowcaseBrainRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWarRoomRoute: AdminWarRoomRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ChatsRoute: ChatsRoute,
  CoinsRoute: CoinsRoute,
  CopilotRoute: CopilotRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  McpRoute: McpRoute,
  ProfileRoute: ProfileRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  UpgradeRoute: UpgradeRoute,
  VerifyRoute: VerifyRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  ApiHostChatRoute: ApiHostChatRoute,
  ChatHostIdRoute: ChatHostIdRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  HostHostIdRoute: HostHostIdRoute,
  HostInvitesRoute: HostInvitesRoute,
  HostMembersRoute: HostMembersRoute,
  HostOnboardingRoute: HostOnboardingRoute,
  HostPricingRoute: HostPricingRoute,
  HostRoomsRoute: HostRoomsRoute,
  InviteCodeRoute: InviteCodeRoute,
  LegalAcceptableUseRoute: LegalAcceptableUseRoute,
  LegalBillingRoute: LegalBillingRoute,
  LegalContactRoute: LegalContactRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalCreatorsRoute: LegalCreatorsRoute,
  LegalDmcaRoute: LegalDmcaRoute,
  LegalLawEnforcementRoute: LegalLawEnforcementRoute,
  LegalPricingRoute: LegalPricingRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundsRoute: LegalRefundsRoute,
  LegalTermsRoute: LegalTermsRoute,
  LegalTrustRoute: LegalTrustRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute,
  RoomsNewRoute: RoomsNewRoute,
  SoonFeatureRoute: SoonFeatureRoute,
  LegalIndexRoute: LegalIndexRoute,
  RoomsIndexRoute: RoomsIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicDemoChatRoute: ApiPublicDemoChatRoute,
  ChatUserUserIdRoute: ChatUserUserIdRoute,
  ApiPublicHooksShowcaseBrainRoute: ApiPublicHooksShowcaseBrainRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
